### PR TITLE
Add ca_no_verify configuration option.

### PR DESCRIPTION
**Pull request by pparkkin**
Configuration option to disable SSL certificate verification on connections to oVirt.

### CODE REVIEW

**Comment by i11** [comment]
Agree that there is not direct benefit. I don't believe we'll be using it either. But as @pparkkin mentioned it's rather straight forward to add it, and there is no reason why it wouldn't work, as it should have been tested in the client already. Anyway, no stress, it was a suggestion only.

By the way, fog 1.27.0 is out.

**Comment by myoung34** [comment]
I will bump the dependency and push a 1.1.0 release to rubygems some time later tonight.

**Comment by i11** [comment]
Finally! Thank you!

**Comment by pparkkin** [comment]
And thanks for getting the gem out so fast too! Definitely made my life easier.

**Pull request merged**
